### ISSUE TITLE
RLD file can't read. Why?

### ISSUE THREAD

**Issue by mymzc4njm** [marcussacana/RLDManager#10]
(Sorry for bad English)

So, I tried RLDManager.
RLD file is 4ayame00_00_000.rld.
I also found key and RLDKeys.txt exist.
But still fail opan file, Unknown encryption key error.
What should I do?

And Crypt worked, but how I edit file and change crypt→rld?

![1](https://user-images.githubusercontent.com/46631481/177906142-a951b3f9-8049-4a18-b10f-4c0e15426b3f.png)

**Comment by marcussacana** [comment]
You can't edit decrypted scripts, edit the crypted one.
try add the encryption key here: https://github.com/marcussacana/RLDManager/blob/master/RLDManager/Main.cs#L46

**Comment by mymzc4njm** [comment]
> You can't edit decrypted scripts, edit the crypted one. try add the encryption key here: https://github.com/marcussacana/RLDManager/blob/master/RLDManager/Main.cs#L46

Sorry if I misunderstand.
But I already found key, and still can't open rld file with RMGUI.
Could you help me?

Also I don't know why, can't open but can crypt.
So I edited, change name .rld and game crashed.

**Comment by marcussacana** [comment]
You may try this tool as well https://github.com/marcussacana/StringReloads

**Comment by mymzc4njm** [comment]
> You may try this tool as well https://github.com/marcussacana/StringReloads

I'm so sorry.
I don't know what is it, and don't know how use.

Actually I want edit image coord, not text translation.

How about you? Your RMGUI is work success?
Or tell me how convert 4ayame00_00_000.rld.crypt to 4ayame00_00_000.rld.

**Comment by mymzc4njm** [comment]
> You may try this tool as well https://github.com/marcussacana/StringReloads

I'm sorry for bothering you.

I trying make naked patch, but seems like image coord in rld file.
So I found RLDManager, sadly it didn't go well.

![uchikano_2022-07-08_03-32-27-327](https://user-images.githubusercontent.com/46631481/177916248-51747cb4-87cd-43e9-a0a9-e16d64958aaf.png)

**Comment by marcussacana** [comment]
In that case you will need use that crypt file, use the decrypt function in your modified file and will be encrypted again.
Anyway, you will need edit the script with a hex editor,  both, RLDManager and StringReloads only allow translate texts.
But RLD script contains many integers in plain text, you may had lucky by just edit with a hex editor.

**Comment by mymzc4njm** [comment]
> In that case you will need use that crypt file, use the decrypt function in your modified file and will be encrypted again. Anyway, you will need edit the script with a hex editor, both, RLDManager and StringReloads only allow translate texts. But RLD script contains many integers in plain text, you may had lucky by just edit with a hex editor.

Finally! That's all I need.
Thank you so much.

**Comment by marcussacana** [comment]
The problem is just how the RLDManager will know the correct key, you may need edit the tool and remove all unecessary keys to the tool allways use the correct one.
