### ISSUE TITLE
Unknown encryption key error after version 1.0.28

### ISSUE THREAD

**Issue by hentaitaku** [marcussacana/RLDManager#11]
Hello after version 1.0.28 will i get unknown encryption key error, have key in RLDKeys.txt
When i use version 1.0.28 can i open the file and see text no errors.
Think this is a bug.

**Comment by marcussacana** [comment]
https://github.com/marcussacana/RLDManager/blob/master/RLDManager/Main.cs#L15
the code still there.

**Comment by hentaitaku** [comment]
I know think the error is in some code you added or did you change the.compiler version.
After that the RLDKeys will not be read or code gives error all time.

Use Windows 11 Pro
This rld can i open with 1.0.28 release and newer versions give back the error.

Here the file i use from latest game released last month.
https://www.mediafire.com/file/t5csuo0hut7n0bb/game-rld.rar/file
