### ISSUE TITLE
Missing text - "Little bug"

### ISSUE THREAD

**Issue by Tfausx** [marcussacana/RLDManager#5]
Hello marcus, i hope you have been having a good day! I was doing some test of this tool on some games releases what uses ExHIBIT engine, especifically, Sakura no Mori 2 and Honoguraki Toki no Hate Yori, on both releases, as show in the screens attached of this issue, there's a missing text in some parts (for example, in the first script of Hnoguraki there's should be 5 texts and the tool only show 2), on other side, in the prologue archive (0_0720_00.rld) you doesn't get any text, justo $noname$, if there's a way you can fix those 2 errors, will be a great help to start a translation project! On other side, this "problems" doesn't seems to be present in Sakura No Mori 1 (english release) as far as i can see
![Honoguraki Toki no Hate Yori](https://user-images.githubusercontent.com/29191836/85491093-4b8f3b80-b5a9-11ea-8130-02549c3ba609.png)
![mori 2](https://user-images.githubusercontent.com/29191836/85491099-4e8a2c00-b5a9-11ea-9053-ca3c57ea9d7f.png)

On other side, i sent you all the scripts files of both games, if you need more to check or the full game, let me know it!

Honoguraki scripts:
https://drive.google.com/file/d/1D6M3JcLZNdCROK1JKdEoGf6RsPqmqAhn/view?usp=sharing

Sakura no mori 2 scripts:
https://drive.google.com/file/d/1GXCgrKLr0HFDIgJ9WaXldSBtKRPW6zck/view?usp=sharing

Have a good day and thanks for everything!

**Comment by marcussacana** [comment]
No surprises, this engine script is a little dynamic, usually every game needs to be verified if this tool is detecting the text correctly, even if your other game still display the text, maybe he don't show everything, so before release the translation you must test your patch.

**Comment by marcussacana** [comment]
I did a update, check it, but keep in mind maybe some lines will be ignored by the tool, this is something that I can't fix while I don't found where, this mean, you must test it and report if you found any problem like that before.
anyway, test it and close the issue if works.
If you found any problem like that again, you can re-open the issue if you want.

**Comment by Tfausx** [comment]
Seems pretty solid right now! Thanks again marcus! If i find another problem, i will give you a touch!

Thank you very much again and i hope you have a great day!
