### ISSUE TITLE
Extract texto to txt file

### ISSUE THREAD

**Issue by javiert239** [marcussacana/RLDManager#6]
Hi, this tools is very useful for my projects.

But is there any way to just extract the text of the rld files to a txt file with this tool?

I found that if you crypt a rld file, the result file contain all the string, but there are a lot of unreadable characters, so it's imposible to clean up that file (and in tried many times with regex).

**Comment by marcussacana** [comment]
You're looking for https://github.com/marcussacana/SacanaWrapper
