### ISSUE TITLE
Modify more than just the dialogues

### ISSUE THREAD

**Issue by javiert239** [marcussacana/RLDManager#7]
Hello Marcus, I hope you are well!

I know the rld files have more than just the dialogues. For example, the names of the images that are displaying on screen.
That's exactly what I want to modify (to solve some issues I'm having with changing the images in Magical Marriage Lunatics).

There is any way I can modify that with this tool?

By the way, I only need to change some characters, but the length of the names of the images will be the same.

**Comment by marcussacana** [comment]
Change this function and made him return allways false
https://github.com/marcussacana/RLDManager/blob/master/RLDManager/Main.cs#L159

**Comment by javiert239** [comment]
I made this changes:
![2](https://user-images.githubusercontent.com/35937688/164732476-945abd56-0f8a-4dd5-81f0-5b8dae2070f4.PNG)

But that only change this:
![1](https://user-images.githubusercontent.com/35937688/164732530-7b06e18b-2fd3-46ea-ba60-5846bfcdc407.PNG)

**Comment by marcussacana** [comment]
Yup, that seems to don't works very well, in this case there's nothing much that you can do.
You should change the code in this case to just decrypt/encrypt the script to you, then you can modify the file
manually with an hex editor.
if you run the RLDManager with a debugger attached the script will be dumped, like here:
https://github.com/marcussacana/RLDManager/blob/master/RLDManager/Main.cs#L38-L42

You need just write the function to open your modified script and encrypt it again.

**Comment by javiert239** [comment]
Well, I don't have any idea of how to change the code so just decrypt/encrypt the scripts.

I don't know a thing about C#, I struggle just to make the changes you suggest at first hahaha.

**Comment by marcussacana** [comment]
Comment this line: `if (System.Diagnostics.Debugger.IsAttached)` (put // in the begin of the line)
Add before or after this line
https://github.com/marcussacana/RLDManager/blob/master/RLDManager/Main.cs#L215
this command:
`Output = System.IO.File.ReadAllBytes("Dump.rld");`
Then the tool will allways decrypt/encrypt the script to a Dump.rld file in the tool directory.

**Comment by javiert239** [comment]
Yes, it worked.

Unfortunately, the scripts didn't worked as I expected. The only images they call, are the masks.

Well, it was worth it to try.

Thanks as always Marcus.
