### ISSUE TITLE
How to open .crypt file

### ISSUE THREAD

**Issue by JamesYuuu** [marcussacana/RLDManager#8]
I have used find key function to find the key of the game, I tried to open the rld files, it still said unknown encryption key. I used the crypt function and the rld key, it changed to ,crypt file. How can I open it or how can I use the key? Thank you so much

**Comment by marcussacana** [comment]
As you can see, the tool look for the "RLDKeys.txt" file, after you found the encryption key just create an txt file with your key
https://github.com/marcussacana/RLDManager/blob/9dafd79df6a642486c5ab812560a4785e01addc5/RLDManager/Main.cs#L15-L17

**Comment by JamesYuuu** [comment]
> As you can see, the tool look for the "RLDKeys.txt" file, after you found the encryption key just create an txt file with your key
> 
> https://github.com/marcussacana/RLDManager/blob/9dafd79df6a642486c5ab812560a4785e01addc5/RLDManager/Main.cs#L15-L17

It is strange as the file alright exists, and I find something more weird, the key is different between different script in the same game, does it is the reason why I can't open the script?

**Comment by JamesYuuu** [comment]
And is it possible to open def.rld or cgmode.rld in Imouto Paradise 3? I can use the key you provided to open the script, but I can't open the cgmode.rld.

**Comment by marcussacana** [comment]
usually def.rld has his own key, different from general scripts.

**Comment by JamesYuuu** [comment]
> usually def.rld has his own key, different from general scripts.

I'm trying to find how ExHIBIT engine merge the CG and さぶん(sorry I don't know how the say it in english) together, so I was trying to check def.rld. I guess I should use find the key function for def.rld and find the particular key for def.rld?

**Comment by marcussacana** [comment]
yup

**Comment by JamesYuuu** [comment]
> yup

Really thank you so much. I guess it was almost midnight in Brazil. Wish you a good night!
