### ISSUE TITLE
The rld file cannot be opened

### ISSUE THREAD

**Issue by canyeweishang** [marcussacana/RLDManager#9]
I've found the key but still show the Unknow Encryption Key。
Here is the text file
[rld.zip](https://github.com/marcussacana/RLDManager/files/8919014/rld.zip)

**Comment by marcussacana** [comment]
you must update the tool keys in his code or put in a RLDKeys.txt file in the directory.

**Comment by canyeweishang** [comment]
The RLDKeys.txt file is already in the directory
![7P$088%)T27H07AI PQ91R8](https://user-images.githubusercontent.com/103740149/174076748-5ac2c724-9257-426d-a270-fe09b5adc55f.png)

**Comment by marcussacana** [comment]
You find the key of the same file that you tried open? 
usually some RLD files have a different key.

**Comment by canyeweishang** [comment]
Yes, I tried to open the same file
![(VDC 3T%J(CVTL7G R@U}OI](https://user-images.githubusercontent.com/103740149/174078756-81ff7538-c31c-4e64-8cb9-7854f486d3f3.png)

**Comment by canyeweishang** [comment]
Different keys were also found but the Unknow Encryption Key is still displayed after putting it into the RLDKeys .txt file

> You find the key of the same file that you tried open? usually some RLD files have a different key.

**Comment by marcussacana** [comment]
try use the arc_conv to find the key, maybe there's a bug with the key finder.

**Comment by canyeweishang** [comment]
The keys found by different tools are the same, and they are all 0xCB23AD1

**Comment by marcussacana** [comment]
should be a bug then.

**Comment by marcussacana** [comment]
no time to check it right now.

**Comment by canyeweishang** [comment]
Okay, thanks for your answer
